### PR TITLE
update readme with CI integration steps

### PR DESCRIPTION
**Pull request by xolaz**
docs...

### CODE REVIEW

**Comment by jborrey** [comment]
@xolaz are you still working on this or should we close?

**Comment by xolaz** [comment]
we should probably merge, I'll rebase

**Comment by jborrey** [comment]
What does this add to the docs that don't already exist? Seems like just the command at the start of the README? Or am I missing something?

**Comment by xolaz** [comment]
I added it based on feedback from people using Salus for the first time. The docs need general updating, but in this case they were looking for an obvious header with a what to run.

**Comment by jborrey** [comment]
Okay I see. If it will be useful to others, then we should keep it.

Few ideas:
  - `coinbase/salus pulls the docker image` --> `That command will automatically pull the the Salus image published on Docker Hub.`
  - Recommend pinning the image in their configuration to a specific Salus version (and probably update the command for latest SHA). This will ensure people don't get surprises if we make breaking changes and give them a bit more defense in the case that DockerHub/CB's ability to publish new versions is compromised.
  - I remember there is that bizarre that bizarre gotcha with running Salus in CircleCI - you might want to mention using Salus's own CircleCI config as a reference.
  - When [the orb stuff gets sorted out](https://github.com/coinbase/salus/issues/39) we should add a link to this section.

**Comment by heimdall-asguard** [comment]
Review Error for nishils @ 2019-06-04 04:26:11 UTC
User cannot review their own commit

**Comment by heimdall-asguard** [comment]
Review Error for dnyu @ 2019-06-04 04:43:06 UTC
User must have write permissions to review

**Comment by heimdall-asguard** [comment]
Review Error for dnyu @ 2019-06-04 05:09:40 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Pull request merged**
