### PR TITLE
Brakeman bump 4.9.1 

### PR DESCRIPTION
**Pull request by ghbren**
Upgrade brakeman and Gem dependencies.

### CODE REVIEW

**Review by joshua-ostrom — APPROVED** [review]
Looks good to me.

**Comment by heimdall-asguard** [comment]
Review Error for joshua-ostrom @ 2020-09-23 22:29:23 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by joshua-ostrom — APPROVED** [review]
Re-approving

**Comment by heimdall-asguard** [comment]
Review Error for joshua-ostrom @ 2020-09-23 22:37:27 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by joshua-ostrom — APPROVED** [review]
LGTM

**Comment by heimdall-asguard** [comment]
Review Error for joshua-ostrom @ 2020-09-23 22:38:34 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by joshua-ostrom — APPROVED** [review]

**Pull request merged**
