### PR TITLE
version bump to 2.10.15

### PR DESCRIPTION
**Pull request by ghbren**

### CODE REVIEW

**Review by egonz — APPROVED** [review]
Looks good

**Comment by heimdall-asguard** [comment]
Review Error for egonz @ 2021-02-02 17:22:14 UTC
User must have write permissions to review

**Review by egonz — APPROVED** [review]
Looks good.

**Comment by heimdall-asguard** [comment]
Review Error for egonz @ 2021-02-02 19:18:54 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by egonz — APPROVED** [review]
LGTM. Trying again to approve.

**Pull request merged**
