### PR TITLE
Upgrade semgrep to v0.48.0

### PR DESCRIPTION
**Pull request by kiwiz**

### CODE REVIEW

**Comment by ghbren** [comment]
could you merge with master?

**Comment by kiwiz** [comment]
@ghbren all done!

**Comment by ghbren** [comment]
@kiwiz Have you tested running the new semgrep from salus?  It seems like in the past there were command line option changes or something, so that updating the version alone wasn't working.

**Comment by kiwiz** [comment]
Not extensively - I've verified that the tests pass and we're running Salus with semgrep 0.53 internally. We're only making use of the `--json` output format, however. How can I build confidence in this upgrade?

**Comment by ghbren** [comment]
Hi @kiwiz Would you be able to update this PR to the newest Semgrep version?

**Comment by kiwiz** [comment]
Updated to 0.56.0 - I'll do some testing on Monday.

**Comment by ghbren** [comment]
@kiwiz Hi Kai, we appreciate your semgrep upgrade PR, but another external user submitted a PR to update semgrep to a newer version and to disable version check.  So we will probably need to close your semgrep PRs.

**Pull request closed without merging**
