### PR TITLE
added Acronym for Salus

### PR DESCRIPTION
**Pull request by ghbren**
Added acronym for Salus in README

### CODE REVIEW

**Comment by jborrey** [comment]
Since when was this a thing?

**Comment by ghbren** [comment]
> Since when was this a thing?

Should it be something else?

**Comment by jborrey** [comment]
I just don't recall there ever being an acronym.
When I named Salus, it was just the Roman Goddess.

If you want some actual trivia, it was going to be called Samus (after Samus Aran) but then I didn't want to think about the copyright infringement etc etc. Salus was a good alternative.

The acronym might help people understand the goal quickly though, so 👍 .

**Comment by xolaz** [comment]
@jborrey we jokingly made one up back in Jan and then realized it fits in really nicely with what Salus does.

**Comment by nishils** [comment]
Yea, this is definitely a backronym

**Pull request merged**
