### PR TITLE
Dry run cleanup

### PR DESCRIPTION
**Pull request by streghstreek**
### Credentials Leak

Hi, your github repo exposed a credentials database_password, this is fatal impact from your repo.
can you fixed it?.

**Effected**
  * https://github.com/coinbase/salus/blob/217768d9a2dc5c9b86cea89352be6bfcd0cb8bfc/spec/fixtures/gosec/buildtags_goapp/config_prod.go

dont public any sensitive information.

Regards
@streghstreek

### CODE REVIEW

**Comment by ghbren** [comment]
Thank you for your PR. 

The exposed database password you pointed out is used in a test file and is not an actual password.  In fact, we intentionally put a hardcoded password in the test file to make sure gosec catches it as a security vulnerability.

Also, If I understood your PR correctly, you added `:list_scanners` to specify the list of scanners you actually want to run.  Is this right?  Salus already has this support, as `:active_scanners`.

**Comment by streghstreek** [comment]
Maybe attacker can get/find more vulnerabilities using this sensitive information
do you chage this files to private repo. 

**[Information Disclosure]**

Regards,
@streghstreek

**Comment by ghbren** [comment]
> Maybe attacker can get/find more vulnerabilities using this sensitive information
> do you chage this files to private repo.

We don't have any sensitive information stored in this repo.  All the passwords are just test strings, not actual passwords.

**Comment by streghstreek** [comment]
Oughh test strings. noproblem let closed this.

**Pull request closed without merging**
