### PR TITLE
Upgrade to Ruby 2.4.5

### PR DESCRIPTION
**Pull request by jborrey**

### CODE REVIEW

**Comment by jborrey** [comment]
Fine to merge with failing Salus since it's just a yarn error. NPM shows no vulns.

**Comment by jborrey** [comment]
```
$ npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 1 scanned package
```

**Comment by heimdall-asguard** [comment]
Review Error for xolaz @ 2019-01-04 03:51:57 UTC
User must have write permissions to review

**Comment by heimdall-asguard** [comment]
Review Error for xolaz @ 2019-01-04 04:14:19 UTC
User must have write permissions to review

**Pull request merged**
