### PR TITLE
semgrep: add config option to support external config

### PR DESCRIPTION
**Pull request by DrewDennison**
- Add in `config` option for semgrep to support external config in either a file or url
- bump version of semgrep to 0.10.1
- make `strict` mode configurable

### CODE REVIEW

**Comment by ghbren** [comment]
@DrewDennison Thank you very much for adding the new features.  But there appears to be a bug with the new `- config` option in salus.yaml.
In this salus.yaml
```
scanner_configs:
  Semgrep:
    matches:
      - config: semgrep.yml
        required: true
```
Salus tell me 
```
Required config "semgrep.yml" was not found - 
```
But if I change `required:true` to `forbidden:true`, then the config file not found error is gone.

**Comment by DrewDennison** [comment]
@ghbren thanks for the note. It's actually just bad wording on my end. I updated it to say `Required patterns in config "semgrep.yml" was not found - ` but let me know if you have ideas for more clear language. I also added in a few more tests to match the existing tests for external configs. Cheers!

**Comment by ghbren** [comment]
Could you update semgrep version in Dockerfile?  Thank you.

**Comment by ghbren** [comment]
If I use semgrep directly and there is a parser related error, then semgrep prints out the file name, line number, and relevant code.  

But if I use salus semgrep, the only thing I get is
```
    {
      "status": 3,
      "stderr": "run with --strict and 71 errors occurred during semgrep run; exiting",
      "message": "Call to semgrep failed"
    },
```

Could you update  salus semgrep so that if there is a parser related error, it
1.  prints out file name, line number, and relevant code too
2.  prints out actual error type (like Parser error, lexical error)
3.  prints out all errors?  In one repo, standalone semgrep printed out about 70 errors, but salus semgrep only printed out 3 errors.

Thank you.

**Comment by ghbren** [comment]
> @ghbren thanks for the note. It's actually just bad wording on my end. I updated it to say `Required patterns in config "semgrep.yml" was not found - ` but let me know if you have ideas for more clear language. I also added in a few more tests to match the existing tests for external configs. Cheers!

Sounds great. Thank you very much.

**Comment by DrewDennison** [comment]
yeah let me quickly parse the json output to get the `errors` key to pipe through to salus

**Pull request merged**
